### ISSUE TITLE
Memory leak observed when paging through a large dataset

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-core#41]
1.15.0 for both

Internal customer doing large data sync found an issue when using IUserDeltaCollectionPage and IGroupDeltaCollectionPage. They call GetAsync on the NextPageRequest property for the next page. They are not using the pageiterator. 

### Expected behavior
Paging through large data set doesn't leak memory.

### Actual behavior
GC is not occurring on the pages. Customer observed up to 3gb memory use, and had to create a new client and release the old one to enable GC.

### Steps to reproduce the behavior
Page through a large data set, take a memory dump. 
[AB#7199](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7199)

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1298

After investigations, the `DerivedTypeConveter` was found to cause issues on 2.x.x versions of core and resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/438. Moving from 1.x.x version of 2.x.x should result in also better performance due to migration from NewtonSoft to System.Text.Json on deserialization of large payloads. 

Preview versions of the 3.x.x no longer have the `DerivedTypeConveter` and use discriminator mappings.
