### ISSUE TITLE
Updated Display Name in Teams app is not returned by Graph API search endpoint

### ISSUE THREAD

**Issue by mlsBlue** [microsoftgraph/msgraph-sdk-dotnet-core#423]
I am experiencing weird behaviour with the change of a Team Room name performed in MS Teams Client application that is not showing in Graph API response when I use search endpoint.

Endpoint used: POST https://graph.microsoft.com/v1.0/search/query

### Expected behavior

Change the name of the Team Room in MS Teams
Use POST https://graph.microsoft.com/v1.0/search/query endpoint to retrieve information about the sites
displayName property in search results should correspond to that change (search index updates are expected and some delay)

### Actual behavior

Change the name of the Team Room in MS Teams
Use POST https://graph.microsoft.com/v1.0/search/query endpoint to retrieve information about the sites
displayName property in search results is not shown for days
When I access the Sharepoint site/Group page new name is not visible there until I refresh the page two times (some caching thing probably)
Shortly after that Graph API will return the updated name in the respone

### Steps to reproduce the behavior

Change the name of the Team Room in MS Teams Client app (Windows 10, Teams app version: 1.5.00.11163 (64-bit))
Wait for some time for search index to be updated
Use POST https://graph.microsoft.com/v1.0/search/query endpoint to retrieve information about the sites 
displayName property is still showing the old name

**Comment by andrueastman** [comment]
Hey @mlsBlue,

Thanks for raising this issue. 

As this issue seems to be API related, any chance you could post the issue at the link below so that we may get feedback from the relevant API owners on the intended functionality?

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-search.html

It would be great if you could post back the link to the question created here so that future users may be able to find the link as well. Closing this for now and will reopen in the event anything SDK related is brought up.

**Comment by mlsBlue** [comment]
I created the question on link posted in the answer above.

https://docs.microsoft.com/en-us/answers/idea/850438/updated-display-name-in-teams-app-is-not-returned.html
