### ISSUE TITLE
Providing a baseUrl with a '?' to GraphServiceClient doesn't work as expected

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/msgraph-sdk-dotnet-core#59]
### Expected behavior
HttpRequest uses baseUrl from GraphServiceClient unmodified and appends query parameters separately:

From Javascript api call:
![image](https://user-images.githubusercontent.com/24302614/68062016-e0fd5880-fcc4-11e9-99c3-8cf89300f0d2.png)

### Actual behavior
HttpRequest contains a pre-populated Query option with part of the baseUrl:
![image](https://user-images.githubusercontent.com/24302614/68061987-cc20c500-fcc4-11e9-95e0-5bcdf6cc6dac.png)

### Steps to reproduce the behavior
1. Clone https://aka.ms/wgt
2. Run SampleTest UWP app
3. Search for 'Alex' in PeoplePicker

If using network sniffer, you'll see incorrect request is sent, you can also see this setting a breakpoint on line 48 in MockProvider.cs.

![image](https://user-images.githubusercontent.com/24302614/68062051-20c44000-fcc5-11e9-9163-9a65eb6d51e9.png)

Pulling down the core SDK unit tests, I can confirm this behavior within the SDK itself outside of our specific implementation details (see more in comment below).

This is the same construction/usage used with the JavaScript Graph SDK done in our other toolkit [here](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/master/src/mock/MockProvider.ts#L80), which works fine. 
[AB#7202](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7202)

**Comment by michael-hawker** [comment]
If you add these two tests related to a Proxy baseUrl, you can see they fail:
```csharp
        [Fact]
        public void BaseRequest_InitializeWithProxyBaseUrl()
        {
            var proxyUrl = "https://proxy.apisandbox.msdn.microsoft.com/svc?url=https://graph.microsoft.com/beta";

            var baseRequest = new BaseRequest(proxyUrl, this.baseClient);

            Assert.Equal(new Uri(proxyUrl), new Uri(baseRequest.RequestUrl));
            Assert.Equal(0, baseRequest.QueryOptions.Count);
            Assert.NotNull(baseRequest.Client.AuthenticationProvider);
            Assert.NotNull(baseRequest.GetHttpRequestMessage().GetRequestContext().ClientRequestId);
            Assert.Equal(baseRequest.GetHttpRequestMessage().GetMiddlewareOption<AuthenticationHandlerOption>().AuthenticationProvider, baseRequest.Client.AuthenticationProvider);
        }

        [Fact]
        public void BaseRequest_InitializeWithProxyWithOptions()
        {
            var proxyUrl = "https://proxy.apisandbox.msdn.microsoft.com/svc?url=https://graph.microsoft.com/beta";
            var baseUrl = string.Concat(proxyUrl, "/me/drive/items/id");

            var options = new List<Option>
            {
                new QueryOption("key3", "value3"),
                new HeaderOption("header", "value"),
            };

            var baseRequest = new BaseRequest(baseUrl, this.baseClient, options);

            Assert.Equal(new Uri(baseUrl), new Uri(baseRequest.RequestUrl));
            Assert.Equal(1, baseRequest.QueryOptions.Count);
            Assert.True(baseRequest.QueryOptions[0].Name.Equals("key3") && baseRequest.QueryOptions[0].Value.Equals("value3"));
            Assert.Equal(1, baseRequest.Headers.Count);
            Assert.True(baseRequest.Headers[0].Name.Equals("header") && baseRequest.Headers[0].Value.Equals("value"));
            Assert.NotNull(baseRequest.Client.AuthenticationProvider);
            Assert.NotNull(baseRequest.GetHttpRequestMessage().GetRequestContext().ClientRequestId);
            Assert.Equal(baseRequest.GetHttpRequestMessage().GetMiddlewareOption<AuthenticationHandlerOption>().AuthenticationProvider, baseRequest.Client.AuthenticationProvider);
            Assert.Equal(baseRequest.GetHttpRequestMessage().RequestUri.ToString(), string.Concat(baseUrl, "?key3=value3"));
        }
```

Looks like problems with assumptions made in the [BaseRequest InitializeUrl method call](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/BaseRequest.cs#L42) and the blanking of the query value from the initial baseUrl here: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/BaseRequest.cs#L428

I think this works from the JavaScript SDK, as it's baseUrl is part of the config and shared and only the path is processed for the query bits after: https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/src/GraphRequest.ts#L116 vs. here it appears the whole url is passed and processed each time?

**Comment by darrelmiller** [comment]
@MIchaelMainer When you get a chance, can you take a look at this issue?  Thanks.

**Comment by MIchaelMainer** [comment]
The assumption was that the query options were only ever to be set with the *Request objects after the URL was constructed, and not part of the baseURL. In other words, the baseUrl for the Microsoft Graph service is not expected to have a query parameter. 

InitializeUrl is only expected to be called after all of the request builders have built the URL. Query parameters are not expected to be directly set in the requestUrl, they are expected to be set in the *Request object cstor. InitializeUrl enforces this. 

Does this only impact your tests or is there another scenario impacted by this behavior? Which by the way, we should be doing testing like this for the .NET client (like what we do for GE). We should consider creating a dedicated test proxy instead of using the one for GE. 

I don't think this behavior is necessary for the function of the request builders, but I think any change here would be a breaking one in the case customers have built custom request objects.

**Comment by MIchaelMainer** [comment]
@michael-hawker or anyone else interested in setting up a test proxy for integration testing with the Microsoft Graph client libraries. I'm dropping the general steps here with the intent to clean this up and write up a more full-featured how to guide. 

1) Get yourself a [developer tenant](https://developer.microsoft.com/en-us/office/dev-program#Subscription). 
2) Register an application in your demo tenant using your target app-only permissions - consent with the admin and get the client secret, tenant id, and application id as we'll use that in a later step. 
3) Create an Azure function app. The function needs to support an arbitrary number of optional routes so that it accepts most URLs emitted by the Microsoft Graph client libraries. 

```csharp
public static class Function1
{
    [FunctionName("Function1")]
    public static async Task<HttpResponseMessage> Run(
        [HttpTrigger(AuthorizationLevel.Function, 
            "get", 
            Route = "{p0?}/{p1?}/{p2?}/{p3?}/{p4?}/{p5?}/{p6?}/{p7?}/{p8?}/{p9?}/{p10?}/{p11?}")] HttpRequest req,
        ILogger log)
    {
        log.LogInformation("C# HTTP trigger function processed a request.");
        log.LogInformation($"Request path: {req.Path}");            

        // Configured to target v1.0 by default.        
        var httpClient = GetConfidentialClient();

        string resourcePath = req.Path.Value.TrimStart('/');

        string path = String.Concat(resourcePath, req.QueryString.ToString());

        var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, path);
        return await httpClient.SendAsync(httpRequestMessage);
    }
```

4) In your function app, you need to create a client with the information from step 2. 

```csharp
public static HttpClient GetConfidentialClient()
{
    var authClient = ConfidentialClientApplicationBuilder
            .Create("appid")
            .WithTenantId("tenantid")
            .WithClientSecret("secret")
            .Build();

    ClientCredentialProvider authenticationProvider = new ClientCredentialProvider(authClient);

    return GraphClientFactory.Create(authenticationProvider);
}
```

5) Create a test with a `GraphServiceClient` that uses the test proxy. My local Azure function is at `http://localhost:7071`.

```csharp
[Fact]
public async Task UsersGet()
{
    var graphClient = new GraphServiceClient("http://localhost:7071", null);
    var users = await graphClient.Users.Request().Select("displayname").GetAsync();
    Assert.NotNull(users);
}
```

This approach works for the non /me scenarios. We'd need to setup an admin consented delegated app that uses the username password provider to enable /me. To enable destructive testing (write), we'd want to implement the testing from private CI.

**Comment by michael-hawker** [comment]
Thanks @MIchaelMainer, I think that's a great approach for certain testing scenarios, but involves a lot of extra steps.

The beauty of Graph Explorer and the environment there is that it just lets you call the Graph and test things out.  The MockProvider we built around that for the [Microsoft Graph Toolkit](https://aka.ms/mgt) has been invaluable for samples, playgrounds, and demos to show folks how easy it is to use the Graph and see how things behave before they go spend time to go build an app.  At that point, they could go setup a test tenant and setup their own test service like you've shown.

Unfortunately, due to this bug, this same setup to create this scenario doesn't work the same for the C# SDK as it does the JavaScript one, which makes it difficult to show the same easy samples and demos for our [XAML C# controls](https://aka.ms/wgt).

I'll dig into seeing why my 'workaround' didn't work in the other call, but it'd be good to discuss later if it makes sense to just pull out or modify the code that's stripping the query string vs. refactoring the baseUrl out.

Are there plans later to align the V1 and Beta SDKs such that calls can be swapped between either endpoint like the JavaScript SDK?  As this type of thing would fit into that type of re-architecture.

**Comment by MIchaelMainer** [comment]
> Are there plans later to align the V1 and Beta SDKs such that calls can be swapped between either endpoint like the JavaScript SDK? As this type of thing would fit into that type of re-architecture.

You can do this if you just use the Core SDK. If you are using the generated parts of the SDK, this is possible, but is not advisable since you'd need to take a dependency on the beta endpoint client to make that happen. The beta endpoint client has lot of features that are in various states of completeness so we wouldn't direct developers to use it. If we only provided models and didn't generate request builders, which is the scenario for the JS SDK, we could do this.

**Comment by darrelmiller** [comment]
@michael-hawker   I think a better option than setting the baseUrl to include the query parameter would be to add a custom piece of middleware that takes the RequestUrl and generates a new RequestUrl during the process of sending the request.  I don't think we would want to try and "fix" the code to allow query parameters in the baseURL.

**Comment by michael-hawker** [comment]
@darrelmiller that seems like a lot of extra overhead to be able to connect to the mock environment.  Is there a reason the C# SDK isn't supporting the same structure that the JS SDK does for the end-point and swapping between V1 and Beta end-points?

**Comment by michael-hawker** [comment]
Copying my workaround from other issue. I think as long as this'll work with any updates in the future, we should be good, this seems pretty robust:

> Alright, finally found a great way to use the proxy without having to dig through the Graph SDK by just pre-pending it in the delegate itself. In this manner the Graph SDK just works as it does and doesn't have to know anything about the proxy. This seems to work in all cases now. 🙂

```cs
new GraphServiceClient(
    new DelegateAuthenticationProvider((requestMessage) =>
{
     var requestUri = requestMessage.RequestUri.ToString();

    // Prepend Proxy Service URI to our request
    requestMessage.RequestUri = new Uri(PROXY_URL + HttpUtility.UrlEncode(requestUri));

    // Add Auth Bearer, etc...
```

**Comment by andrueastman** [comment]
This should be addressed with Kiota based SDK with the use of the `RequestInformation` abstraction in favor of `BaseRequest`. 

The use of the URI templating mechanisms allows the baseUrl to be setup as described in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/59#issuecomment-550533637

https://github.com/microsoft/kiota-abstractions-dotnet/pull/31 validates this as well and will close this issue.
