### ISSUE TITLE
Evaluate improving batching support

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-dotnet-core#612]
Evaluate improving batching support based on the work @svrooij did [here](https://github.com/svrooij/msgraph-sdk-dotnet-batching/).

We could integrate this in the .NET core library and also evaluate a similar approach for all other languages we support.

By the way, incredible work @svrooij. Kudos!

**Comment by svrooij** [comment]
Thanks for the compliment @maisarissi I was not sure if this would be something that you would consider to be implemented in the main library. Hence the fact of me creating an extension library.

Our company is probably one of the big time users of batching (we even build a custom in-house graph client because the official client did not support batching just yet).

If you're open for this change, I can convert the code to a PR? Would need some help creating the tests for it though. But until then users can just install my extension from [nuget](https://www.nuget.org/packages/SvRooij.Graph.Batching/). And have better batching support from the start.

**Comment by maisarissi** [comment]
Yes! Absolutely @svrooij .

We would love to get this as a PR. Our engineering team can review it and collaborate with you in case any changes are needed as well as help creating tests.

**Comment by bwosborne2** [comment]
@maisarissi 
Has there been any consideration of adding something similar to the PHP SDK?

**Comment by maisarissi** [comment]
Hi @bwosborne2 , for PHP implementation you can follow the issue https://github.com/microsoftgraph/msgraph-sdk-php-core/issues/129
