### ISSUE TITLE
Change in Error Code for Image Not Found in Microsoft Graph API

### ISSUE THREAD

**Issue by saha-anik** [microsoftgraph/msgraph-sdk-dotnet-core#796]
We have recently observed a change in the error code returned by the Microsoft Graph API when an image is not found for a user. Previously, the error code was "ImageNotFound", but it now returns "ErrorEntityNotFound" for the same scenario.

###Expected Behavior:
Previously, when an image was not found for a user, the Graph API would return the following error:

```
Code: ImageNotFound
Message: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.
```
###Actual behavior:
As of the latest interaction with the API, the error message has changed to:

```
Code: ErrorEntityNotFound
Message: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ImageNotFoundException' was thrown.
```
Despite the message being the same, the error code has changed from "ImageNotFound" to "ErrorEntityNotFound".

###Steps to Reproduce:
Make a request to the Graph API to retrieve an image for a user that does not have an image set.
Observe the error code and message returned by the API.
Impact:
This change in the error code impacts our error handling logic, as our application specifically checks for the "ImageNotFound" error code to handle these cases gracefully.

Request:
We would like clarification on whether this change in the error code is an intentional update in the Graph API or an unexpected bug. If it's an intentional change, could you provide guidance on how to adapt to this new error code? 

Environment:
Graph Nuget Package Version: 4.33.0
Programming language/SDK: [Specify language/SDK version]
Additional Context:
Error occurred on [Date: 2024-01-18]
Looking forward to your guidance and support on this matter.

**Comment by andrueastman** [comment]
Thanks for raising this @saha-anik,

I believe rather than reading the `Code` it should be enough to read the status code of the response/error to confirm that the image is not present. In this scenario it should be 404. 
However, as this repo is mainly intended for client SDK related issues, we may not be best placed to answer if the change in error code data from the API is intended or not. I would suggest asking a question at the link below to get feedback from the API owners. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
